### ISSUE TITLE
Failed to import "nonebot_plugin_spark_gpt"

### ISSUE THREAD

**Issue by Ibighai** [canxin121/Spark-GPT#16]
插件载入失败。

06-17 13:47:26 [ERROR] nonebot | Failed to import "nonebot_plugin_spark_gpt"
Traceback (most recent call last):
  File "D:\QQBOT\QQ1\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\__init__.py", line 4, in <module>
    from .common.render.render import md_to_pic
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\common\render\render.py", line 10, in <module>
    from ...poe_pw.pwframework import pwfw
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\poe_pw\pwframework.py", line 3, in <module>
    from .config import poe_persistor
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\poe_pw\config.py", line 8, in <module>
    from ..common.config import spark_persistor
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\common\config.py", line 198, in <module>
    spark_persistor = SparkPersistor()
  File "D:\QQBOT\QQ1\.venv\lib\site-packages\nonebot_plugin_spark_gpt\common\config.py", line 182, in __init__
    self.num_limit = int(getattr(get_config, "spark_limit", 350))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by Joyboy-s** [comment]
怎么解决的大佬

**Comment by Ibighai** [comment]
放弃解决。。。
