### ISSUE TITLE
导入两个插件都失败，求大佬指导

### ISSUE THREAD

**Issue by VAHua** [canxin121/Spark-GPT#43]
```
3-13 14:15:50 [ERROR] nonebot | Failed to import "nonebot_plugin_web_config"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path        
    main_content = runpy.run_path(main_path,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\qqbot\robot\bot.py", line 46, in <module>
    nonebot.load_plugin("nonebot_plugin_spark_gpt")   # spark_gpt
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin       
    return manager.load_plugin(module_path)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin   
    module = importlib.import_module(name)
  File "D:\Program Files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module   
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_spark_gpt\__init__.py", line
 6, in <module>
    require("nonebot_plugin_web_config")
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 179, in require
    plugin = load_plugin(name)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin       
    return manager.load_plugin(module_path)
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin   
    module = importlib.import_module(name)
  File "D:\Program Files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module   
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_web_config\__init__.py", lin
e 1, in <module>
    from . import web_ui
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_web_config\web_ui\__init__.p
y", line 1, in <module>
    from . import router
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_web_config\web_ui\router.py"
, line 25, in <module>
    manager = LoginManager(
TypeError: LoginManager.__init__() got an unexpected keyword argument 'custom_exception'
03-13 14:15:50 [ERROR] nonebot | Failed to import "nonebot_plugin_spark_gpt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path        
    main_content = runpy.run_path(main_path,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\qqbot\robot\bot.py", line 46, in <module>
    nonebot.load_plugin("nonebot_plugin_spark_gpt")   # spark_gpt
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin       
    return manager.load_plugin(module_path)
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin   
    module = importlib.import_module(name)
  File "D:\Program Files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module   
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_spark_gpt\__init__.py", line
 6, in <module>
    require("nonebot_plugin_web_config")
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_web_config"!
```

**Comment by homuraLan** [comment]
跟一个，同款错误

**Comment by Zhou-Shilin** [comment]
同

**Comment by KaMmySuma** [comment]
同
